#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "landing"
name = "YunoHost Landing Page"

description.en = "Yunohost landing page"
description.fr = "Page d'accueil de Yunohost"

version = "1.0~ynh1"

maintainers = ["salamandar"]

[upstream]
license = "GPLv3"
website = "https://yunohost.org"
demo = "https://yunohost.org"

code = "https://github.com/yunohost/landingpage"

[integration]
yunohost = ">= 11.2"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/landingpage"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "python3",
        "python3-venv",
    ]
